'use client';
import { useState } from 'react';
import { ArrowUpRight, ArrowDown, Plus, Star, ArrowRight } from 'lucide-react';
import { RadioGroup, RadioGroupItem } from '@/components/ui/radio-group';
import { Carousel, CarouselContent, CarouselItem, CarouselPrevious, CarouselNext } from '@/components/ui/carousel';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
const money=(n:number)=>n.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const kits=[{qty:1,name:'O seu primeiro ritual',price:247},{qty:2,name:'Cuidado em dobro',price:449},{qty:3,name:'Seu ritual completo',price:629}];
const gallery=[{id:2,label:'Um momento de pausa'},{id:7,label:'Essencial para levar'},{id:8,label:'Sempre por perto'},{id:4,label:'A delicadeza da textura'},{id:9,label:'Cuidado que acompanha você'}];
const institutional=['Sobre Nós','Trocas e Devoluções','Política de Privacidade','Política de Frete','Política de Cookies','Termos de Serviço','Aviso Legal'];
const support=['Fale Conosco','Falar com consultor','FAQ','Formas de Pagamento','Rastrear pedido'];
const info:Record<string,string>={
'Sobre Nós':'Estamos preparando a apresentação da loja. Em breve, você poderá conhecer nossa história e nossa proposta de cuidado.',
'Trocas e Devoluções':'A política de trocas e devoluções será disponibilizada antes da abertura das vendas.',
'Política de Privacidade':'A política de privacidade está em preparação e será disponibilizada antes da abertura das vendas.',
'Política de Frete':'As regiões atendidas, os prazos e as condições de frete serão informados após a definição da operação de entrega.',
'Política de Cookies':'As informações sobre cookies serão disponibilizadas de acordo com os serviços utilizados na versão final da loja.',
'Termos de Serviço':'Os termos de serviço serão disponibilizados antes da abertura das vendas.',
'Aviso Legal':'As informações legais e a identificação da empresa responsável serão disponibilizadas na versão final da loja.',
'Fale Conosco':'O canal de atendimento será disponibilizado em breve.',
'Falar com consultor':'O contato do consultor será disponibilizado em breve.',
'Formas de Pagamento':'As formas de pagamento serão informadas após a configuração da loja.',
'Rastrear pedido':'O acesso ao rastreamento será disponibilizado após a definição da operação de entrega.'};
export default function Home(){
 const [selected,setSelected]=useState('1');const [photo,setPhoto]=useState(3);const [modal,setModal]=useState<string|null>(null);
 const kit=kits.find(k=>String(k.qty)===selected)!;
 return <>
 <div className="announcement">Cuidado coreano. Um momento só seu.</div>
 <header className="header"><nav aria-label="Navegação principal"><a href="#produto">O essencial</a><a href="#ritual">Seu ritual</a></nav><a className="brand" href="#inicio" aria-label="Dr. Althea — início"><img src="/images/logo.webp" alt="Dr. Althea" width="3545" height="1182"/></a><a className="header-link" href="#funciona">A beleza do cuidado <ArrowUpRight size={15}/></a></header>
 <main id="inicio">
 <section className="hero"><div className="hero-copy"><span className="eyebrow">DR. ALTHEA / DAILY SKIN ESSENTIALS</span><div><h1>Um respiro.<br/>Para a sua pele.</h1><p>Hidratação leve. Cuidado delicado.<br/>Redescubra a beleza de uma rotina simples.</p><a className="button" href="#produto">Conheça o 345 Relief Cream <ArrowUpRight size={18}/></a></div><a className="scroll-link" href="#produto"><ArrowDown size={15}/> O cuidado começa aqui</a></div><div className="hero-photo hero-campaign"><img src="/images/campaign-9.png" alt="Modelo segurando o 345 Relief Cream em uma composição clara" fetchPriority="high" width="1122" height="1402"/><div className="photo-caption"><span>345 RELIEF CREAM</span><span>O ESSENCIAL, TODOS OS DIAS.</span></div></div></section>
 <section className="product section product-v2" id="produto"><div className="product-gallery"><div className="product-visual"><span className="eyebrow image-label">SEU ESSENCIAL DIÁRIO / 01</span><img src={`/images/campaign-${photo}.png`} alt="345 Relief Cream 50 ml — fotografia do produto" width="1122" height="1402"/><span className="product-volume">DR. ALTHEA PRO LAB · 50 ML</span></div><div className="thumbnails" aria-label="Fotos do produto">{[3,1,4,5].map((n,i)=><button key={n} onClick={()=>setPhoto(n)} aria-label={`Ver foto ${i+1} do produto`} aria-pressed={photo===n}><img src={`/images/campaign-${n}.png`} alt="" loading="lazy" width="1122" height="1402"/></button>)}</div></div><div className="product-copy"><span className="eyebrow green">HIDRATAÇÃO & CONFORTO</span><h2>345<br/>Relief Cream</h2><p className="product-subtitle">Um gesto leve. Um cuidado que fica.</p><p>Hidratante facial de textura leve para uma rotina de cuidado com a pele sensível. Niacinamida, pantenol e ceramida NP em uma fórmula para todos os dias.</p><div className="kit-heading"><span>Escolha seu ritual</span><span>50 ml por unidade</span></div><RadioGroup value={selected} onValueChange={v=>setSelected(String(v))} aria-label="Escolha um kit ilustrativo" className="kit-options">{kits.map(k=><label className={`kit-option ${selected===String(k.qty)?'selected':''}`} key={k.qty}><RadioGroupItem value={String(k.qty)} aria-label={`${k.qty} ${k.qty===1?'unidade':'unidades'}`}/><span><strong>{k.qty} {k.qty===1?'unidade':'unidades'}</strong><small>{k.name}</small></span><span className="kit-price">{money(k.price)}<small>{money(k.price/k.qty)} / un.</small></span></label>)}</RadioGroup><div className="price" aria-live="polite">{money(kit.price)} <span>{kit.qty} × 50 ml</span></div><Button className="button product-button" onClick={()=>setModal('Comprar')}>Comprar meu kit <ArrowUpRight size={18}/></Button><p className="demo-label">Prévia de design · valores fictícios, compra indisponível.</p></div></section>
 <section className="ugc section" id="experiencias"><div className="section-heading"><div><span className="eyebrow">NA VIDA, NA ROTINA</span><h2>Pequenos gestos.<br/>Diferentes momentos.</h2></div><p>O cuidado encontra espaço no seu dia.</p></div><div className="ugc-grid">{[{n:6,title:'O toque do cuidado',sub:'Um momento para a pele'},{n:8,title:'Vai com você',sub:'O essencial na sua nécessaire'},{n:9,title:'Seu ritual, seu tempo',sub:'Beleza nos pequenos gestos'}].map(x=><figure key={x.n}><img src={`/images/campaign-${x.n}.png`} alt={x.title} loading="lazy" width="1122" height="1402"/><figcaption><h3>{x.title}</h3><p>{x.sub}</p></figcaption></figure>)}</div><p className="section-note">Imagens editoriais. Vídeos de experiências em breve.</p></section>
 <section className="faq section" id="perguntas"><div><span className="eyebrow">SUAS PERGUNTAS</span><h2>Conheça melhor.<br/>Cuide com calma.</h2></div><div className="questions">{[['Como incluir na minha rotina?','Aplique na etapa de hidratação, sobre a pele limpa, e espalhe suavemente até a absorção. Siga as orientações da embalagem.'],['Qual é a textura do 345 Relief Cream?','Um creme de textura leve, pensado para a hidratação diária.'],['O que vem em cada kit?','As opções desta prévia apresentam 1, 2 ou 3 unidades de 50 ml. Quantidades e preços comerciais ainda serão confirmados.'],['Quando poderei comprar?','Estamos preparando a loja. A disponibilidade, os valores finais e as condições de entrega serão informados antes da abertura das vendas.']].map(([q,a])=><details key={q}><summary>{q}<Plus size={18}/></summary><p>{a}</p></details>)}</div></section>
 <section className="reviews section" id="avaliacoes"><div className="section-heading"><div><span className="eyebrow">AVALIAÇÕES</span><h2>Quem cuida, conta.</h2></div><p className="review-disclaimer">Exemplos fictícios para visualizar o layout.<br/>Não representam experiências de clientes.</p></div><div className="review-grid">{[{name:'Marina',text:'Gostei de reservar alguns minutos do dia só para cuidar de mim. O produto encontrou um lugar na minha rotina.'},{name:'Camila',text:'A apresentação delicada e a proposta de uma rotina simples são o que mais chamaram minha atenção.'},{name:'Beatriz',text:'Um pequeno ritual que combina com os meus momentos de pausa. Adorei a ideia de levar na nécessaire.'}].map(r=><article key={r.name}><div className="review-stars" aria-label="5 estrelas — exemplo fictício">{[1,2,3,4,5].map(n=><Star key={n} size={13}/>)}</div><blockquote>“{r.text}”</blockquote><div className="review-person"><span>{r.name}<small>Personagem fictícia</small></span><span>EXEMPLO</span></div></article>)}</div></section>
 <section className="why section" id="funciona"><div className="why-photo"><img src="/images/campaign-4.png" alt="345 Relief Cream acompanhado de uma textura de creme" loading="lazy" width="1122" height="1402"/></div><div className="why-copy"><span className="eyebrow">POR QUE FUNCIONA</span><h2>Leve na textura.<br/>Essencial no cuidado.</h2><p>Segundo a Dr. Althea, a fórmula combina hidratação, suporte à barreira de umidade e cuidado com a aparência da textura da pele.</p><div className="benefit"><span>01</span><div><h3>Hidratação equilibrada</h3><p>Ajuda a manter o conforto sem uma sensação pesada.</p></div></div><div className="benefit"><span>02</span><div><h3>Barreira de umidade</h3><p>Um cuidado diário para apoiar a hidratação da pele.</p></div></div><div className="benefit"><span>03</span><div><h3>Textura mais suave</h3><p>Ajuda a suavizar a aparência da textura irregular.</p></div></div><a className="source-link" href="https://doctoraltheaglobal.com/products/345-relief-cream" target="_blank" rel="noreferrer">Conheça as informações do fabricante <ArrowUpRight size={13}/></a></div></section>
 <section className="ritual" id="ritual"><div className="ritual-photo"><img src="/images/campaign-6.png" alt="Aplicação delicada de creme no rosto" loading="lazy" width="1122" height="1402"/></div><div className="ritual-copy"><span className="eyebrow">MODO DE USO</span><h2>Uma pausa.<br/>Um pequeno gesto.<br/>Seu momento.</h2><p>Faça da hidratação um momento simples da sua rotina.</p>{[['Prepare a pele','Comece com a pele limpa.'],['Aplique com delicadeza','Espalhe uma quantidade adequada no rosto.'],['Deixe absorver','Pressione suavemente e siga sua rotina.']].map(([title,desc],i)=><div className="ritual-step" key={title}><span>0{i+1}</span><p>{title}<br/><small>{desc}</small></p></div>)}<span className="ritual-note">Siga as orientações de uso da embalagem.</span></div></section>
 <section className="technology section" id="tecnologias"><div className="section-heading"><div><span className="eyebrow">TECNOLOGIAS / A FORMULAÇÃO</span><h2>O cuidado está<br/>na combinação.</h2></div><p>Ingredientes que fazem parte<br/>da fórmula do 345 Relief Cream.</p></div><div className="technology-grid">{[{num:'01',name:'Niacinamida',desc:'Presente na composição, ao lado de ingredientes hidratantes.'},{num:'02',name:'Pantenol + ceramida NP',desc:'Parte da combinação de ingredientes para o cuidado diário.'},{num:'03',name:'Centella + beta-glucana',desc:'Também integram a lista de ingredientes da fórmula.'}].map(t=><article key={t.num}><span className="technology-number">{t.num}</span><h3>{t.name}</h3><p>{t.desc}</p></article>)}</div></section>
 <section className="moments section" id="galeria"><div className="section-heading"><div><span className="eyebrow">UM OLHAR MAIS DE PERTO</span><h2>O essencial, em cena.</h2></div><p>Texturas, luz e pequenos rituais.</p></div><Carousel className="editorial-carousel" opts={{align:'start',loop:false}} aria-label="Galeria de imagens do produto"><CarouselContent>{gallery.map(g=><CarouselItem key={g.id} className="gallery-slide"><figure><img src={`/images/campaign-${g.id}.png`} alt={g.label} loading="lazy" width="1122" height="1402"/><figcaption>{g.label}</figcaption></figure></CarouselItem>)}</CarouselContent><div className="carousel-controls"><span>Arraste para explorar</span><div><CarouselPrevious aria-label="Imagem anterior"/><CarouselNext aria-label="Próxima imagem"/></div></div></Carousel></section>
 <section className="closing"><span className="eyebrow">O ESSENCIAL, TODOS OS DIAS.</span><h2>Seu próximo ritual<br/>começa com um gesto.</h2><a className="button" href="#produto">Escolha seu kit <ArrowUpRight size={18}/></a></section>
 </main><footer className="footer-v2"><div className="footer-grid"><div className="footer-intro"><a className="footer-brand" href="#inicio"><img src="/images/logo.webp" alt="Dr. Althea" width="3545" height="1182"/></a><p>Uma rotina simples.<br/>Um cuidado especial.</p><span className="eyebrow">SKINCARE / DAILY ESSENTIALS</span></div><div><h3>Institucional</h3>{institutional.map(label=><button key={label} onClick={()=>setModal(label)}>{label}</button>)}</div><div><h3>Atendimento</h3>{support.map(label=>label==='FAQ'?<a key={label} href="#perguntas">FAQ</a>:<button key={label} onClick={()=>setModal(label)}>{label}</button>)}</div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} · Dr. Althea — conceito da loja</span><span>BRASIL · PORTUGUÊS</span><a href="#inicio">Voltar ao início ↑</a></div></footer>
 <Dialog open={modal!==null} onOpenChange={open=>{if(!open)setModal(null)}}><DialogContent className="information-dialog"><DialogTitle>{modal==='Comprar'?'Seu kit na prévia':modal}</DialogTitle><DialogDescription>{modal==='Comprar'?`${kit.qty} ${kit.qty===1?'unidade':'unidades'} de 50 ml · ${money(kit.price)}. Este valor é fictício e serve apenas para avaliar o design. Nenhum pedido ou pagamento será realizado.`:modal?info[modal]:''}</DialogDescription><Button variant="outline" onClick={()=>setModal(null)}>Voltar para a página <ArrowRight size={16}/></Button></DialogContent></Dialog>
 </>;
}
