import { ArrowUpRight, ArrowDown, Plus } from 'lucide-react';
const shop='https://evg0ar-mr.myshopify.com/products/345-relief-cream';
export default function Home(){return <>
<div className="announcement">Cuidado coreano. Um momento só seu.</div>
<header className="header"><nav aria-label="Navegação principal"><a href="#produto">O essencial</a><a href="#ritual">Seu ritual</a></nav><a className="brand" href="#inicio" aria-label="Dr. Althea — início"><img src="/images/logo.webp" alt="Dr. Althea" width="3545" height="1182"/></a><a className="header-link" href="#filosofia">A beleza do cuidado <ArrowUpRight size={15}/></a></header>
<main id="inicio"><section className="hero"><div className="hero-copy"><span className="eyebrow">DR. ALTHEA / DAILY SKIN ESSENTIALS</span><div><h1>Um respiro.<br/>Para a sua pele.</h1><p>Hidratação leve. Cuidado delicado.<br/>Redescubra a beleza de uma rotina simples.</p><a className="button" href="#produto">Conheça o 345 Relief Cream <ArrowUpRight size={18}/></a></div><a className="scroll-link" href="#filosofia"><ArrowDown size={15}/> O cuidado começa aqui</a></div><div className="hero-photo"><img src="/images/editorial.jpg" alt="Textura cremosa do 345 Relief Cream sobre a embalagem" fetchPriority="high"/><div className="photo-caption"><span>345 RELIEF CREAM</span><span>TEXTURA LEVE. CUIDADO ESSENCIAL.</span></div></div></section>
<section className="philosophy section" id="filosofia"><span className="eyebrow">MENOS EXCESSOS. MAIS CUIDADO.</span><h2>A sua pele não precisa de mais.<br/>Precisa do que faz sentido.</h2><p>Um convite para desacelerar e transformar o cuidado diário em um momento de conexão. Fórmulas que encontram seu lugar na rotina. Texturas que você sente vontade de usar.</p><div className="principles"><span>01 — Hidratar</span><span>02 — Acolher</span><span>03 — Simplificar</span></div></section>
<section className="product section" id="produto"><div className="product-visual"><span className="eyebrow image-label">SEU ESSENCIAL DIÁRIO / 01</span><img src="/images/product.jpg" alt="Dr. Althea 345 Relief Cream, bisnaga de 50 ml" loading="lazy" width="1400" height="1400"/><span className="product-volume">DR. ALTHEA PRO LAB · 50 ML</span></div><div className="product-copy"><span className="eyebrow green">HIDRATAÇÃO & CONFORTO</span><h2>345<br/>Relief Cream</h2><p className="product-subtitle">Um gesto leve.<br/>Um cuidado que fica.</p><p>Hidratante facial de textura suave para acompanhar a sua rotina. Uma combinação de niacinamida, pantenol e ceramida NP em um cuidado diário com a pele.</p><dl className="specs"><div><dt>Textura</dt><dd>Creme leve</dd></div><div><dt>Na rotina</dt><dd>Etapa de hidratação</dd></div><div><dt>Conteúdo</dt><dd>50 ml</dd></div></dl><div className="price">R$ 247,00 <span>50 ml / 1.69 fl. oz.</span></div><a className="button product-button" href={shop} target="_blank" rel="noreferrer">Ver disponibilidade na loja <ArrowUpRight size={18}/></a><p className="availability">Disponibilidade e condições de entrega na loja.</p></div></section>
<section className="formula section" id="formula"><div className="section-heading"><div><span className="eyebrow">POR DENTRO DO ESSENCIAL</span><h2>Cuidado em<br/>cada detalhe.</h2></div><p>Uma fórmula para conhecer com calma.<br/>Três dos ingredientes que fazem parte<br/>do 345 Relief Cream.</p></div><div className="ingredients"><article><span className="ingredient-number">01</span><h3>Niacinamida</h3><p>Um dos ingredientes que compõem a fórmula do seu cuidado diário.</p></article><article><span className="ingredient-number">02</span><h3>Pantenol</h3><p>Parte da combinação de ingredientes da etapa de hidratação.</p></article><article><span className="ingredient-number">03</span><h3>Ceramida NP</h3><p>Presente na fórmula, junto à niacinamida e ao pantenol.</p></article></div></section>
<section className="ritual" id="ritual"><div className="ritual-photo"><img src="/images/editorial.jpg" alt="Detalhe da textura e da embalagem do hidratante facial" loading="lazy"/></div><div className="ritual-copy"><span className="eyebrow">O SEU RITUAL / TODOS OS DIAS</span><h2>Uma pausa.<br/>Um pequeno gesto.<br/>Seu momento.</h2><p>Depois da limpeza e dos seus cuidados habituais, aplique uma quantidade adequada no rosto e espalhe suavemente até a absorção.</p><div className="ritual-step"><span>01</span><p>Prepare a pele<br/><small>Comece com a pele limpa.</small></p></div><div className="ritual-step"><span>02</span><p>Aplique com delicadeza<br/><small>Espalhe o creme suavemente.</small></p></div><div className="ritual-step"><span>03</span><p>Respeite o seu tempo<br/><small>Deixe absorver e siga sua rotina.</small></p></div><span className="ritual-note">Siga as orientações de uso da embalagem.</span></div></section>
<section className="faq section"><div><span className="eyebrow">PARA CONHECER MELHOR</span><h2>Cuidado também<br/>é informação.</h2></div><div className="questions"><details><summary>Como incluir na minha rotina? <Plus size={18}/></summary><p>Utilize na etapa de hidratação, após a limpeza e os cuidados anteriores. Consulte as orientações da embalagem do produto.</p></details><details><summary>Qual é o tamanho do produto? <Plus size={18}/></summary><p>O 345 Relief Cream apresentado nesta página contém 50 ml.</p></details><details><summary>Onde consultar disponibilidade e entrega? <Plus size={18}/></summary><p>Acesse a página do produto na loja para consultar a disponibilidade. As condições de entrega precisam estar confirmadas antes de concluir a compra.</p><a href={shop} target="_blank" rel="noreferrer">Ir para o produto <ArrowUpRight size={14}/></a></details></div></section>
<section className="closing"><span className="eyebrow">O ESSENCIAL, TODOS OS DIAS.</span><h2>Deixe o cuidado<br/>encontrar a sua pele.</h2><a className="text-link" href="#produto">Explore o 345 Relief Cream <ArrowUpRight size={20}/></a></section></main>
<footer><a className="footer-brand" href="#inicio"><img src="/images/logo.webp" alt="Dr. Althea" width="3545" height="1182"/></a><div className="footer-links"><a href="#produto">O essencial</a><a href="#formula">A fórmula</a><a href="#ritual">Seu ritual</a></div><div className="footer-bottom"><span>Uma rotina simples. Um cuidado especial.</span><span>BRASIL · PORTUGUÊS</span><a href="#inicio">Voltar ao início ↑</a></div></footer></>}
